version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  preBuild:
    commands:
      - yarn install
  build:
    commands:
      - yarn run export
artifacts:
  baseDirectory: out
  files:
    - '**/*'
cache:
  paths:
    - node_modules/**/*
