/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_content_delivery_bucket": "tcrb.onlinebanking-backoffice.com-dev",
    "aws_content_delivery_bucket_region": "ap-southeast-1",
    "aws_content_delivery_url": "http://tcrb.onlinebanking-backoffice.com-dev.s3-website-ap-southeast-1.amazonaws.com"
};


export default awsmobile;
